### ISSUE TITLE
No such file or directory (os err or 2)

### ISSUE THREAD

**Issue by TornaxO7** [webdesus/fs_extra#65]
I'm getting the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "No such file or directory (os err
or 2)" }', src/main.rs:4:82
```
although it should work (I think).

## Reproduction steps
Create test directory:
```
mkdir -p /tmp/rofl1/yeet
touch /tmp/rofl1/test.txt
touch /tmp/rofl1/yeet/bruh.txt
```
`Cargo.toml`
```toml
[package]
name = "rust_tmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
```
`src/main.rs`
```rust
use fs_extra::dir::CopyOptions;

fn main() {
    fs_extra::dir::copy("/tmp/rofl1", "/tmp/rofl2", &CopyOptions::new()).unwrap();
}
```

What am I doing wrong?
